 //1 _ DFS  - DEPTH FIRST SEARCH (DEPTH WISE)
// a. INORDER TRAVERSAL=  LEFT -> ROOT ->RIGHT
// b. PREOREDER TRAVERSAL=   ROOT -> LEFT-> RIGHT
// c. POSTOREDER TRAVERSAL=  LEFT -> RIGHT -> ROOT

 // 2_ BFS  - BREADTH FIRST SEARCH (LEVEL WISE)
 