<<<<<<< HEAD
 //1 _ DFS  - DEPTH FIRST SEARCH (DEPTH WISE)
// a. INORDER TRAVERSAL=  LEFT -> ROOT ->RIGHT
// b. PREOREDER TRAVERSAL=   ROOT -> LEFT-> RIGHT
// c. POSTOREDER TRAVERSAL=  LEFT -> RIGHT -> ROOT

 // 2_ BFS  - BREADTH FIRST SEARCH (LEVEL WISE)
=======
 //1 _ DFS  - DEPTH FIRST SEARCH (DEPTH WISE)
// a. INORDER TRAVERSAL=  LEFT -> ROOT ->RIGHT
// b. PREOREDER TRAVERSAL=   ROOT -> LEFT-> RIGHT
// c. POSTOREDER TRAVERSAL=  LEFT -> RIGHT -> ROOT

 // 2_ BFS  - BREADTH FIRST SEARCH (LEVEL WISE)
>>>>>>> f8b8a2dcf8691bf61c6bc66fd4062749d41f17e1
 